# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  

  go:
    container_name: go
    image: sushmithabkongi/golang-api:api_V_1.0
    
    # build the Dockerfile, alternatively use an image.
    build:
      context: .
      dockerfile: Dockerfile
   
    restart: always
    ports:
      - "5002:5002"
    

    volumes:
      - .:/app/
      #dbdata: 
      # create the volume for persisting data.
  node_n:
    build: ./Server-UI
    image: sushmithabkongi/ui:react
    container_name: node_n
    
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    networks:
      - default

    restart: always